version: 2
updates:
  # 游댏 Seguridad en dependencias Node.js (JavaScript/React/Next.js)
  - package-ecosystem: "npm"
    directory: "/"                  # Ra칤z del proyecto (package.json est치 aqu칤)
    schedule:
      interval: "daily"             # Revisi칩n diaria para m치xima protecci칩n
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"   # Solo actualiza dependencias directas
    groups:
      js-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  # 游댢 GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"                  # Workflows en .github/workflows/
    schedule:
      interval: "weekly"
